### ISSUE TITLE
[INFO] FOSS Explorer

### ISSUE THREAD

**Issue by Wabri** [lamorbidamacchina/calcola-tasse#1]
Ciao!

La tua repository è stata selezionata dalla nostra redazione per il format "FOSS Explorer" di [Schrodinger Hat](https://www.youtube.com/channel/UC1QLLgrGrPmlaFhS0orykCA), una rubrica del nostro talk show riguardo il software development e il mondo open source italiano, e verrà mostrata nella puntata di Martedì 26 Maggio in diretta sul canale [Twitch](https://www.twitch.tv/schrodinger_hat) e [YouTube](https://www.youtube.com/channel/UC1QLLgrGrPmlaFhS0orykCA) alle ore 13.00.

Il tuo lavoro ci è piaciuto molto e speriamo che questo possa aiutare a fornire visibilità al tuo lavoro ;)
Se per te va bene, la includeremo nella nostra top15 bisettimanale!

A presto!

**Comment by lamorbidamacchina** [comment]
Ciao Gabriele
ti ringrazio, va benissimo.
Spero di riuscire a vedervi live domani, altrimenti recupererò in differita :)
Buona serata
Simone

Il giorno lun 25 mag 2020 alle ore 18:21 GabrielePuliti
<notifications@github.com> ha scritto:
>
> Ciao!
>
> La tua repository è stata selezionata dalla nostra redazione per il format "FOSS Explorer" di Schrodinger Hat, una rubrica del nostro talk show riguardo il software development e il mondo open source italiano, e verrà mostrata nella puntata di Martedì 26 Maggio in diretta sul canale Twitch e YouTube alle ore 13.00.
>
> Il tuo lavoro ci è piaciuto molto e speriamo che questo possa aiutare a fornire visibilità al tuo lavoro ;)
> Se per te va bene, la includeremo nella nostra top15 bisettimanale!
>
> A presto!
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub, or unsubscribe.



-- 
Simone Ricci

M: +39 328 69 39 940
www.digitalbuilders.it
www.linkedin.com/in/simonericci/
